# Generated by Django 4.1.3 on 2022-11-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cometela', '0007_viandatamaño'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('viandas', models.ManyToManyField(to='Cometela.viandatamaño')),
            ],
        ),
    ]
