# Generated by Django 4.1.3 on 2022-11-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cometela', '0008_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
