# Generated by Django 4.1.3 on 2022-11-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cometela', '0009_delete_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamaño',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], max_length=20, null=True),
        ),
    ]
