# Generated by Django 4.1.3 on 2022-11-15 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vianda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('TRADICIONAL', 'Tradicional'), ('VEGANA', 'Vegana'), ('LIGHT', 'Light')], max_length=20)),
                ('precio_media', models.IntegerField()),
                ('precio_entera', models.IntegerField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cometela.dia')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.IntegerField(default=0)),
                ('entera', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vianda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cometela.vianda')),
            ],
        ),
    ]
