# Generated by Django 4.1.3 on 2022-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cometela', '0002_rename_precio_entera_vianda_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vianda',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vianda',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vianda',
            name='tamaño',
            field=models.CharField(choices=[('MEDIA', 'Media'), ('ENTERA', 'Entera')], max_length=20, null=True),
        ),
    ]
