# Generated by Django 4.1.3 on 2022-11-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cometela', '0006_tamaño_delete_viandatamaño'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViandaTamaño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cometela.tamaño')),
                ('vianda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cometela.vianda')),
            ],
        ),
    ]
