# Generated by Django 4.1.3 on 2022-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cometela', '0011_alter_viandatamaño_tamaño_alter_viandatamaño_vianda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vianda',
            name='dia',
            field=models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vianda',
            name='tipo',
            field=models.CharField(choices=[('TRADICIONAL', 'Tradicional'), ('VEGGIE', 'Veggie'), ('LIGHT', 'Light')], max_length=20),
        ),
    ]
