# Generated by Django 4.1.3 on 2022-12-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
